### ISSUE TITLE
pd-queue status: AttributeError

### ISSUE THREAD

**Issue by remiyu** [PagerDuty/pdagent#103]
RHEL: 6.8
Python:  2.6.6
pdagent: v1.4

Attempting to run `pd-queue status` returns the following trace: 
```
pd-queue status
Service Key                           Pending   Success  In Error
=================================================================
key                                     8         0         0
Traceback (most recent call last):
  File "/usr/bin/pd-queue", line 147, in <module>
    main()
  File "/usr/bin/pd-queue", line 135, in main
    args.func(load_agent_config(), parser, args)
  File "/usr/bin/pd-queue", line 123, in _status
    state.get("pending_events", empty_dict).get("count", 0),
AttributeError: 'int' object has no attribute 'get'
```

**Comment by bodgit** [comment]
Also seeing this on RHEL 7.x, seems it only occurs when there are pending events. I wouldn't have noticed it if I didn't have a proxy in the way blocking access to the PagerDuty API.

**Comment by remiyu** [comment]
@bodgit Thanks. Issue was with the proxy as you mentioned. Resolved.

**Comment by bodgit** [comment]
I didn't necessarily say the proxy was the cause, just that by having the agent running without the proxy configured caused a buildup of pending events so I saw the same error as you reported.

You could possibly reproduce this by just blocking the agents access to the PagerDuty API either directly or via a proxy and generating an event or two to create some pending events.

**Comment by remiyu** [comment]
In this case it was a misconfiguration involving the proxy.
