### ISSUE TITLE
Buildup of queue files

### ISSUE THREAD

**Issue by bodgit** [PagerDuty/pdagent#106]
A long running/installed pdagent installation can accrue large numbers of files in the `/var/lib/pdagent/outqueue/*` directories, especially `/var/lib/pdagent/outqueue/suc/` (assuming all things are working correctly). If left unmanaged this can fill the disk up, use up all of the inodes, etc.

There doesn't seem to be any shipped cron job/systemd timer/... in the package to clean these up periodically, it might be an idea to add one.

**Comment by bfg-agoulet** [comment]
I'd like to second this.  Messages in that directory have already been sent, so keeping them indefinitely serves no apparent purpose and has the potential to negatively impact disk utilization on the host.
