### ISSUE TITLE
CertificateError: hostname 'proxy' doesn't match either of '*.pagerduty.com', 'pagerduty.com'

### ISSUE THREAD

**Issue by ricohomewood** [PagerDuty/pdagent#109]
Hello
When running pdagent behind and proxy and adding the relevant env variables to: /lib/systemd/system/pdagent.service and reloading the service and daemon, we get the following error in  /var/log/pdagent/pdagentd.log and the send event doesn't occur:

CertificateError: hostname '192.168.41.85' doesn't match either of '*.pagerduty.com', 'pagerduty.com'

192.168.41.85 refers to a proxy server we are behind:

My setup:
openssl 1.1.0
pdagent: 1.4
python: 2.7.9

the full log below:

  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pdagent/thirdparty/httpswithverify.py", line 120, in connect
    match_hostname(self.sock.getpeercert(), self.host)
  File "/usr/lib/python2.7/dist-packages/pdagent/thirdparty/ssl_match_hostname.py", line 149, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
CertificateError: hostname '192.168.41.85' doesn't match either of '*.pagerduty.com', 'pagerduty.com'

looks like this is something python is doing to validate the pagerduty site certificate?

**Comment by shellshock1953** [comment]
Have the same problem. Any ideas?

**Comment by ricohomewood** [comment]
This is a know bug.

PD are looking to fix this is their next release of the agent hopefully.

This is a workaround but it is a potential security risk. See here:

https://community.pagerduty.com/t/certificateerror-hostname-proxy-doesnt-match-either-of-pagerduty-com-pagerduty-com/1002/3
