### ISSUE TITLE
Does pdagent still support Python2.6?

### ISSUE THREAD

**Issue by limitusus** [PagerDuty/pdagent#113]
This code should run only on >= Python2.7, since `socket.create_connection()` can receive up to 2 arguments in 2.6.
https://github.com/PagerDuty/pdagent/blob/master/pdagent/thirdparty/httpswithverify.py#L103-L104

**Comment by dobs** [comment]
You're correct that this was probably broken by using `socket.create_connection()` -- ideally we'd have fixed this sooner, but with the upcoming deprecation of Python 2 I'm inclined to close as wontfix.
